/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f429xx.h"
#include "ff.h"
#include "main.h"
#include "simple_spi.h"
void fat_file_init(void);

#define PLL_M  4
#define PLL_N  180
#define PLL_P  0
/*#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/
void config_clock(void)
{
	//1)trurn on the HSE
	RCC->CR |= RCC_CR_HSEON;
	//wait for HSE ready
	while(!(RCC->CR & RCC_CR_HSERDY));
	//2)set the power enable clock and voltage regulator
	RCC->APB1ENR |= RCC_APB1ENR_PWREN;
	PWR->CR |= PWR_CR_VOS;

	//3)config the flash prefetch and latancy related settings
	FLASH->ACR = FLASH_ACR_ICEN | FLASH_ACR_DCEN | FLASH_ACR_PRFTEN |FLASH_ACR_LATENCY_5WS;
	//4)config the prescalars hclk, pclk1, pclk2
	//AHB PR
	RCC->CFGR |= RCC_CFGR_HPRE_DIV2;
	//APB1 PR
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;
	//APB2 PR
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;
	//5) config the main pll
	RCC->PLLCFGR = (PLL_M << 0) | (PLL_N << 6) | (PLL_P << 16) | (RCC_PLLCFGR_PLLSRC_HSE);
    //6)enable PLL and wait for it to become ready
	RCC->CR |= RCC_CR_PLLON;
	while(!(RCC->CR & RCC_CR_PLLRDY));
	//7) select the clock source and wait for it to be set
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL);
}

uint32_t SysTick_Config(uint32_t ticks)
{
 if ((ticks - 1UL) > SysTick_LOAD_RELOAD_Msk)
 {
   return (1UL);                                                   /* Reload value impossible */
 }

 SysTick->LOAD  = (uint32_t)(ticks - 1UL);                         /* set reload register */
 SCB->SHPR[(((uint32_t)SysTick_IRQn) & 0xFUL)-4UL] = (uint8_t)((((1UL << 4U) - 1UL) << 4U) & (uint32_t)0xFFUL);
 SysTick->VAL   = 0UL;                                             /* Load the SysTick Counter Value */
 SysTick->CTRL  = SysTick_CTRL_CLKSOURCE_Msk |
                  SysTick_CTRL_TICKINT_Msk   |
                  SysTick_CTRL_ENABLE_Msk;                         /* Enable SysTick IRQ and SysTick Timer */
 return (0UL);                                                     /* Function successful */
}

uint32_t tickCount = 0;
FATFS fs;          // File system object
FIL file;          // File object
FRESULT res;
int main(void)
{
    /* Loop forever */
	config_clock();
	SysTick_Config(90000);
	spi_gpio_init();
	spi_peripheral_clock_init();
	spi_init();
	fat_file_init();

	res = f_mount(&fs, "", 1);

	for(;;);
}

uint32_t HAL_GetTick(void)
{
	return tickCount;
}

void SysTick_Handler(void)
{
	tickCount++;
}
