/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rtc.h"

#define BUFF_LEN   20

static void display_rtc_calander(void);

uint8_t time_buff[BUFF_LEN] = {0};
uint8_t date_buff[BUFF_LEN] = {0};

int hr = 0,mnt = 0,sec = 0, mon = 0, day = 0, year = 0;

int main(void)
{
    /* Loop forever */
	rtc_init();


	for(;;)
	{
		display_rtc_calander();
	}
}

static void display_rtc_calander(void)
{
	hr = rtc_convert_bcd2bin(rtc_time_get_hour());
	mnt = rtc_convert_bcd2bin(rtc_time_get_minute());
	sec = rtc_convert_bcd2bin(rtc_time_get_second());

	mon = rtc_convert_bcd2bin(rtc_date_get_month());
	day = rtc_convert_bcd2bin(rtc_date_get_day());
	year = rtc_convert_bcd2bin(rtc_date_get_year());
}


