/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "dma.h"
#include "adc_dma.h"
#include "stm32_f429xx.h"
#include "tim.h"

extern uint8_t g_transfer_complete;

uint8_t srcBuf[10] = "1234567890";
uint8_t dstBuf[10] = {0};

void delay(void)
{
	for(int i = 0;i < 90000;i++);
}

int main(void)
{
	int j = 1;
	//dma2MemToMemCfg();
	//dma_transfer_start(srcBuf,dstBuf,sizeof(dstBuf));
	//adc_init();
	//adc_tim_data_init();
	tim2_pa0_pa1_pwm_init();
	tim2_pa0_pa1_pwm_set_dutycycle(1,100);
	tim2_pa0_pa1_pwm_set_dutycycle(2,2);
	for(;;)
	{
		while(j)
		{
			tim2_pa0_pa1_pwm_set_dutycycle(1,j++);
			if(j >= 100) j= 1;
			delay();
		}

	}
}

void DMA2_Stream0_IRQHandler(void)
{
	/*check if transfer complete occured*/
	if((DMA2->LISR) & LISR_TCIF0)
	{
		g_transfer_complete = 1;
		/*clear flag*/
		DMA2->LIFCR |= LIFCR_CTCIF0;
	}
}

