/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "dma.h"
#include "adc_dma.h"

extern uint8_t g_transfer_complete;

uint8_t srcBuf[10] = "1234567890";
uint8_t dstBuf[10] = {0};

int main(void)
{
	//dma2MemToMemCfg();
	//dma_transfer_start(srcBuf,dstBuf,sizeof(dstBuf));
	adc_init();
	for(;;);
}
