/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "timer.h"
#include "uart.h"
#include "stm32_f429xx.h"
#include "cm4.h"
uint8_t flag = 0;
uint16_t cntVal = 0;

void clock_init(void)
{
	RCC->CR |= (1 << 0);//enable HSI
	while(!(RCC->CR & (1 << 1)));

	RCC->CFGR |= RCC_CFGR_HPRE_DIV1;
	//APB1 PR
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV4;
	//APB2 PR
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;

	//bydefault HSI is selcted ad system clock
}

void init_low_power_mode(void)
{
	//enable sleep on exit
	SCB->SCR |= (1 << 1);
}

int main(void)
{
    /* Loop forever */
	clock_init();
	gpio_init();
	timer6_init();
	//This function should be called after all the initialization.
	init_low_power_mode();
	for(;;);
}

void TIM6_DAC_IRQHandler(void)
{
	uart_send_string("From ISR!\r\n");
/*	if(flag)
	{
		set();
	}
	else
	{
		clear();
	}
	cntVal = getCNTval();

	flag = !flag;*/
}
