/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "dma.h"
#include "adc_dma.h"
#include "stm32_f429xx.h"
#include "uart_dma.h"

extern uint8_t g_rx_complete;
extern uint8_t g_uart_complete;
extern char uart_data_buffer[UART_DATA_BUF_SIZE];
extern uint8_t g_transfer_complete;

uint8_t srcBuf[10] = "1234567890";
uint8_t dstBuf[10] = {0};
char msg_buf[] = "initialization cmplt!";
int main(void)
{
	//dma2MemToMemCfg();
	//dma_transfer_start(srcBuf,dstBuf,sizeof(dstBuf));
	//adc_init();
	//adc_tim_data_init();
	uart2_rx_tx_init();
	dma1_init();
	dma1_stream5_uart_rx_config();
	dma1_stream6_uart_tx_config(msg_buf,sizeof(msg_buf));
	for(;;);
}

void DMA2_Stream0_IRQHandler(void)
{
	/*check if transfer complete occured*/
	if((DMA2->LISR) & LISR_TCIF0)
	{
		g_transfer_complete = 1;
		/*clear flag*/
		DMA2->LIFCR |= LIFCR_CTCIF0;
	}
}

