/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rtc.h"
#include "stm32_f429xx.h"

#define BUFF_LEN   20

static void display_rtc_calander(void);

uint8_t time_buff[BUFF_LEN] = {0};
uint8_t date_buff[BUFF_LEN] = {0};

int hr = 0,mnt = 0,sec = 0, mon = 0, day = 0, year = 0;

int main(void)
{
    /* Loop forever */
	rtc_init();
	rtc_alarm_init();
	rtc_timestamp_init();
	for(;;)
	{
		//display_rtc_calander();
	}
}

static void display_rtc_calander(void)
{
	hr = rtc_convert_bcd2bin(rtc_time_get_hour());
	mnt = rtc_convert_bcd2bin(rtc_time_get_minute());
	sec = rtc_convert_bcd2bin(rtc_time_get_second());

	mon = rtc_convert_bcd2bin(rtc_date_get_month());
	day = rtc_convert_bcd2bin(rtc_date_get_day());
	year = rtc_convert_bcd2bin(rtc_date_get_year());
}

static void alarm_callback(void)
{
	(void)0;
}
void RTC_Alarm_IRQHandler(void)
{
	/*Get alarm interrupt source enable status*/
	if((RTC->CR & CR_ALRAIE) != 0)
	{
		/*Get the pending status of the Alarm interrupt*/
		if((RTC->ISR & ISR_ALRAF) != 0)
		{
			alarm_callback();
			/*Clear the Alarm interrupt pending bit*/
			RTC->ISR &= ~ISR_INIT;
		}
	}
	/*Clear the EXIT's flag for RTC Alarm*/
	EXTI->PR |= (1U << 17U);
}

void timestamp_event_callback(void)
{
	(void)0;
}
void TAMP_STAMP_IRQHandler(void)
{
	/*Get timesatmp interupt source enable status*/
	if((RTC->CR & CR_TSIE) != 0)
	{
		/*Get the pending status of the timesatmp interrupt*/
		if((RTC->ISR & ISR_TSF) != 0)
		{
			timestamp_event_callback();
			/*Clear the timesatmp interrupt pending bit*/
			RTC->ISR &= ~ISR_TSF;
		}
	}
	/*Clear the EXIT's flag for RTC Alarm*/
	EXTI->PR |= (1U << 21U);
}


