/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO/gpio.h"
#include "FLASH/flash.h"

uint32_t ex_data = 0x45679999;

int main(void)
{
    /* Loop forever */
	init_gpio();

	Flash_WriteData(USER_FLASH_ADD + 12,(uint8_t*)&ex_data,4);

	Flash_EraseSector(12);
	for(;;)
	{
		if(readButton() == 1)
		{
			while(0);
		}
	}
}
